title: 'Caffeine Algorithm'
description: 'Uma organização de desenvolvimento que ama cafeína e algoritmos.'
keywords: 'caffeine algorithm, desenvolvimento, organização, cafeína, algoritmos, python, csharp, java, go, html5, css3, android'
url: 'https://caffeinealgorithm.com/'
baseurl: '/'

development: false

organization:
  name: 'Caffeine Algorithm'
  email: 'caffeinealgorithm@imnelsonsilva.com'
  youtube_id: 'UCdt_qK8rmpxrq942ZFIqxvQ'
  youtube_name: 'CaffeineAlgorithm'
  linkedin: 'caffeinealgorithm'

author:
  name: 'Nelson Silva'
  username: 'imnelsonsilva'
  date_of_birth: 'July 5, 1995'
  phone_number: '+351912585091'
  location: 'Porto, Portugal'
  email: 'contact@imnelsonsilva.com'
  bio: 'The Worst Full Stack/Blockchain Developer'
  linkedin: 'imnelsonsilva'
  github: 'imnelsonsilva'
  instagram: 'imnelsonsilva'
  twitter: 'imnelsonsilva'
  website: 'https://imnelsonsilva.com/'

google:
  analytics: 'UA-76965623-1'
  verify: 'IbdqgDuSqKIZcqbFuLdJIYqliUXDuMSMkW_HlWm_mDw'
  ad_client: 'ca-pub-9627952229249296'
  ad_footer_slot: 9153729361

statcounter:
  project: 10935538
  security: '0176ef5d'

exclude: ['README.md']
