title: 'Caffeine Algorithm'
description: 'Uma organização de desenvolvimento que ama cafeína e algoritmos.'
keywords: 'caffeine algorithm, desenvolvimento, organização, cafeína, algoritmos, python, c#, java, android, html, css, go, javascript, ruby, nscodev, nelson silva'
url: 'https://caffeinealgorithm.com/'
baseurl: '/'

development: false

organization:
  name: 'Caffeine Algorithm'
  email: 'contacto@caffeinealgorithm.com'
  youtube_name: 'CaffeineAlgorithm'
  linkedin: 'caffeinealgorithm'

author:
  name: 'Nelson Silva'
  username: 'nscodev'
  date_of_birth: 'July 5, 1995'
  phone_number: '+351914434573'
  location: 'Porto, Portugal'
  email: 'contact@nscodev.com'
  bio: 'A human. Being. Coffee lover.'
  linkedin: 'nscodev'
  github: 'nscodev'
  instagram: 'nscodev'
  twitter: 'nscodev'
  website: 'https://nscodev.com/'

google:
  analytics: 'UA-76965623-1'
  verify: 'Hd7ercgeU93Jto-kpb1WzxoT08EYihsWHNMoW3YSgG8'
  ad_client: 'ca-pub-9627952229249296'
  ad_footer_slot: 9153729361

exclude: ['README.md']
