title: 'Caffeine Algorithm'
description: 'Uma organização de desenvolvimento que ama cafeína e algoritmos.'
url: 'http://caffeinealgorithm.com/'
baseurl: '/'

development: false

organization:
  name: 'Caffeine Algorithm'
  email: 'caffeinealgorithm@gmail.com'
  google:
    youtube-id: 'UCdt_qK8rmpxrq942ZFIqxvQ'
    youtube-name: 'CaffeineAlgorithm'
    analytics: 'UA-76965623-1'
    verify: 'GXpcyk8cWqpKPhIGcaS1nUaEJ7T_F66Ns1MkX_WRvhU'
    ad-client: 'ca-pub-9627952229249296'
    ad-footer-slot: 9153729361
    ad-sidebar-slot: 6620248568
  github: 'caffeinealgorithm'
  statcounter:
    project: 10935538
    security: 'cce7c3f8'

author:
  name: 'Nelson Silva'
  avatar: 'avatar.png'
  email: 'contact@dnelsonsilvav.com'
  bio: 'The Worst Full Stack Developer'
  linkedin: 'dnelsonsilvav'
  github: 'dnelsonsilvav'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

destination: _site
paginate: 5
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md']