title: 'Caffeine Algorithm'
description: 'Uma organização de desenvolvimento que ama cafeína e algoritmos.'
keywords: 'caffeine algorithm, desenvolvimento, organização, cafeína, algoritmos, python, csharp, java, go, html5, css3, android'
url: 'https://caffeinealgorithm.com/'
baseurl: '/'

development: false

organization:
  name: 'Caffeine Algorithm'
  email: 'caffeinealgorithm@codenelsongslv.com'
  youtube_name: 'CaffeineAlgorithm'
  linkedin: 'caffeinealgorithm'

author:
  name: 'Nelson Silva'
  username: 'codenelsongslv'
  date_of_birth: 'July 5, 1995'
  phone_number: '+351914434573'
  location: 'Porto, Portugal'
  email: 'contact@codenelsongslv.com'
  bio: 'A human. Being. Coffee lover.'
  linkedin: 'codenelsongslv'
  github: 'codenelsongslv'
  instagram: 'codenelsongslv'
  twitter: 'codenelsongslv'
  website: 'https://codenelsongslv.com/'

google:
  analytics: 'UA-76965623-1'
  verify: 'Hd7ercgeU93Jto-kpb1WzxoT08EYihsWHNMoW3YSgG8'
  ad_client: 'ca-pub-9627952229249296'
  ad_footer_slot: 9153729361

statcounter:
  project: 10935538
  security: '0176ef5d'

exclude: ['README.md']
