title: Caffeine Algorithm
description: A development organization that loves caffeine and algorithms.
url: http://caffeinealgorithm.com
permalink: '/:title'
logo: logo.png

sass:
  sass_dir: _sass
  style: compressed

page_ext: md
post_ext: md

page_layout: default
post_layout: post

markdown: kramdown

organization:
  name: Caffeine Algorithm
  # email: contact@caffeinealgorithm.com
  email: caffeinealgorithm@gmail.com
  twitter: caffealgorithm
  google:
    plus: CaffeineAlgorithm
    youtube: CaffeineAlgorithm
    analytics: UA-76965623-1
    verify: GXpcyk8cWqpKPhIGcaS1nUaEJ7T_F66Ns1MkX_WRvhU
    ad-client: ca-pub-9627952229249296
    ad-footer-slot: 9153729361
    ad-sidebar-slot: 7676996160
  github: caffeinealgorithm

author:
  name: Nelson Silva
  avatar: avatar.png
  # email: devwop@caffeinealgorithm.com
  email: devwop@outlook.com
  bio: A developer that breathes caffeine.
  twitter: devwop_
  linkedin: devwop
  github: devwop