title: 'Caffeine Algorithm'
description: 'Uma organização de desenvolvimento que ama cafeína e algoritmos.'
keywords: 'caffeine algorithm, desenvolvimento, organização, cafeína, algoritmos, python, c#, java, android, html, css, go, javascript, ruby, nelsonsilvadev, nelson silva'
url: 'https://caffeinealgorithm.com/'
baseurl: '/'

development: false

organization:
  name: 'Caffeine Algorithm'
  email: 'contacto@caffeinealgorithm.com'
  youtube_name: 'CaffeineAlgorithm'
  linkedin: 'caffeinealgorithm'

author:
  name: 'Nelson Silva'
  username: 'nelsonsilvadev'
  date_of_birth: 'July 5, 1995'
  phone_number: '+351913416022'
  location: 'Porto, Portugal'
  email: 'contact@nelsonsilvadev.com'
  bio: 'A human. Being. Coffee lover.'
  linkedin: 'nelsonsilvadev'
  github: 'nelsonsilvadev'
  instagram: 'nelsonsilvadev'
  twitter: 'nelsonsilvadev'
  website: 'https://nelsonsilvadev.com/'

google:
  analytics: 'UA-76965623-1'
  verify: 'rvDK_K_NrRhzCCOkgAG-jEmFqH8dbCQEX-K22SZY5Uo'
  ad_client: 'ca-pub-9627952229249296'
  ad_footer_slot: 9153729361

exclude: ['README.md']
